// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"gin-design/internal/app/controller"
	"gin-design/internal/app/repo"
	"gin-design/internal/app/router"
	"gin-design/internal/app/service"
	"gin-design/internal/config"
	"gin-design/internal/db"
	"gin-design/internal/pkg/logger"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp(mode string) (*App, error) {
	configConfig, err := config.LoadConfig(mode)
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.NewZapLogger(configConfig)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewGormDB(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(gormDB)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	userRouter := router.NewUserRouter(userController)
	v := router.NewRouters(userRouter)
	app := NewApp(v)
	return app, nil
}

// wire.go:

type App struct {
	Engine  *gin.Engine
	routers []router.Router
}

func NewApp(routers []router.Router) *App {
	return &App{
		Engine:  gin.Default(),
		routers: routers,
	}
}

func (a *App) Run() {

	api := gin.Default().Group("/api")

	a.SetRoute(api)

	a.Engine.Run(":9001")
}

func (a *App) SetRoute(api *gin.RouterGroup) {
	for _, r := range a.routers {
		r.SetRoute(api)
	}
}
