// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/gin-contrib/pprof"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"loan-admin/internal/app/controller"
	"loan-admin/internal/app/data"
	"loan-admin/internal/app/repo"
	"loan-admin/internal/app/router"
	"loan-admin/internal/app/service"
	"loan-admin/internal/config"
	"loan-admin/internal/db"
	"loan-admin/internal/middleware"
	"loan-admin/internal/pkg/logger"
)

import (
	_ "loan-admin/docs"
)

// Injectors from wire.go:

func InitApp(mode string) (*App, error) {
	configConfig, err := config.LoadConfig(mode)
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.NewZapLogger(configConfig)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewGormDB(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	dataData := data.NewData(gormDB)
	userRepo := repo.NewUserRepo(dataData)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	userRouter := router.NewUserRouter(userController)
	acessRepo := repo.NewAccessRepo(dataData)
	accessService := service.NewAccessService(acessRepo)
	accessController := controller.NewAccessController(accessService)
	accessRouter := router.NewAccessRouter(accessController)
	v := router.NewRouters(userRouter, accessRouter)
	app := NewApp(v)
	return app, nil
}

// wire.go:

type App struct {
	Engine  *gin.Engine
	routers []router.Router
}

func NewApp(routers []router.Router) *App {
	return &App{
		Engine:  gin.Default(),
		routers: routers,
	}
}

func (a *App) Run() {

	api := a.Engine.Group("api")

	api.Use(middleware.CORS())

	a.SetRoute(api)

	a.Engine.GET("/health", func(ctx *gin.Context) {
		ctx.JSON(200, gin.H{
			"message": "pong",
		})
	})
	pprof.Register(a.Engine, "/api/pprof")

	a.Engine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	a.Engine.Run(":9001")
}

func (a *App) SetRoute(api *gin.RouterGroup) {
	for _, r := range a.routers {
		r.SetRoute(api)
	}
}
