basePath: /api
consumes:
- application/json
definitions:
  dto.GetUserResp:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: https://api.example.com
info:
  contact: {}
  description: 后台管理系统
  title: 后台管理系统
  version: "1.0"
paths:
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetUserResp'
        "400":
          description: 无效请求
          schema:
            type: string
        "500":
          description: 服务器错误
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户管理  // ✅ 建议使用中文标签分类
produces:
- application/json
schemes:
- https
swagger: "2.0"
